[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Goziri", email = "goziri.dev@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "langchain-openrouter>=0.2.9",
    "pymupdf4llm>=1.28.2",
    "sqlmodel>=0.0.47",
    "structlog>=26.1.0",
]

[project.scripts]
server = "server.main:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.ruff.lint]
select = ["I"]  # isort rules

[tool.ruff.lint.isort]
known-first-party = ["server"]

[tool.pyrefly]
python-interpreter-path = ".venv/bin/python"
